### ISSUE TITLE
What happened

### ISSUE THREAD

**Issue by haakonstorm** [ColumbusCollaboratory/rflow#1]
What happened to rflow? Is it abandonware now or did another project take its place?

**Comment by petegordon** [comment]
We are here.  Last we used it is was working for generating NodeRed nodes from R packages and executing or generating R source code from NodeRed flows using the nodes.

The next thing we have been considering (but have not had time to work on) is how to make the creation of NodeRed flows directly from R Code... but that would require deep understanding of the R AST and relating it back to NodeRed nodes to create the flow from the R source code directly and vise versa.  That is where we left off... we are happy to accept pull requests.

[https://adv-r.hadley.nz/expressions.html#ast](https://adv-r.hadley.nz/expressions.html#ast)
